# Site settings
title: de.NBI metabolomics winterschool 2018
email: denbi-mash@ipb-halle.de
description: > # this means to ignore newlines until "baseurl:"
  Website for the de.NBI metabolomics winterschool 2018
  providing an overview of the event.
baseurl: "/winterschool2018/" # the subpath of your site, e.g. /blog/
url: "https://sneumann.github.com/winterschool2019" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
